version: '3.1'
services:
  mysql-standalone:
    image: 'mysql:8.0.27'
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=book_library
    ports:
      - "3307:3306"
  springboot-docker-container:
    image: book-library
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/book_library?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "admin"
    build:
      context: "./"
      dockerfile: "DockerFile"
    depends_on:
      - mysql-standalone